// <auto-generated />
using System;
using Mango.Services.EmailsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.EmailsAPI.Migrations
{
    [DbContext(typeof(EmailDBContext))]
    partial class EmailDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.EmailsAPI.Model.EmialDto", b =>
                {
                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentTiming")
                        .HasColumnType("datetime2");

                    b.HasKey("EmailID");

                    b.ToTable("Emails");
                });
#pragma warning restore 612, 618
        }
    }
}
